# golangci-lint v2.7.2 (2025-12-14)
version: "2"

run:
  tests: true

linters:
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: snake
          bson: snake

  exclusions:
    rules:
      # Disable strict linters in test files
      - path: _test\.go
        linters:
          - funlen
          - dupl
          - goconst
          - mnd
          - wrapcheck
          - err113
          - gocognit
          - gosec

  default: none
  enable:
    # Core (must have)
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

    # Bug detection
    - bodyclose
    - nilerr
    - nilnesserr
    - nilnil
    - durationcheck
    - errchkjson
    - contextcheck
    - noctx
    - makezero
    - reassign
    - wastedassign
    - forcetypeassert
    - noinlineerr
    - iotamixing
    - gochecksumtype
    - musttag
    - sqlclosecheck
    - rowserrcheck
    - unqueryvet

    # Security
    - gosec

    # Code quality
    - gocognit
    - goconst
    - gocritic
    - unconvert
    - unparam
    - prealloc
    - perfsprint
    - usestdlibvars
    - intrange
    - copyloopvar
    - nestif
    - decorder
    - grouper
    - importas
    - modernize
    - iface

    # Style
    - misspell
    - dupword
    - asciicheck
    - bidichk
    - whitespace
    - dogsled
    - nakedret
    - predeclared
    - errname
    - errorlint
    - funlen
    - lll
    - nonamedreturns
    - godot
    - tagliatelle
    - tagalign
    - nlreturn
    - wsl_v5
    - godoclint
    - godox
    - funcorder

    # Strict error handling
    - err113
    - wrapcheck

    # Magic numbers
    - mnd

    # Testing
    - thelper
    - testpackage
    - testableexamples
    - tparallel
    - usetesting

    # Logging
    - sloglint

    # HTTP
    - canonicalheader

    # Observability
    - spancheck
    - promlinter

    # Lint hygiene
    - nolintlint

    # Other useful
    - asasalint
    - containedctx
    - fatcontext
    - mirror
    - nosprintfhostport
    - gomoddirectives
    - goprintffuncname
    - gocheckcompilerdirectives
    - gochecknoinits
    - exhaustive
    - interfacebloat
    - inamedparam
    - dupl
    - recvcheck
    - exptostd
    - forbidigo
    - protogetter

    # --- Disabled linters (with reasons) ---

    # Too strict / noisy
    # - exhaustruct          # requires ALL struct fields initialized - extremely noisy
    # - varnamelen           # opinionated variable name length rules - often annoying
    # - gochecknoglobals     # forbids all globals - too restrictive, many legitimate uses
    # - paralleltest         # requires t.Parallel() everywhere - can be noisy

    # Redundant with existing linters
    # - cyclop               # cyclomatic complexity - already have gocognit
    # - gocyclo              # cyclomatic complexity - already have gocognit
    # - maintidx             # maintainability index - arbitrary metric, gocognit is better
    # - revive               # golint replacement - gocritic covers similar rules

    # Framework/library specific (enable if using)
    # - arangolint           # ArangoDB client best practices
    # - ginkgolinter         # Ginkgo/Gomega test framework
    # - zerologlint          # zerolog logger
    # - testifylint          # testify assertions - enable if using testify
    # - loggercheck          # kitlog/klog/logr/zap - already have sloglint for slog

    # Needs configuration / project-specific
    # - depguard             # block/allow package imports - needs allowlist config
    # - gomodguard           # block/allow module dependencies - needs config
    # - goheader             # file header checks - only for license boilerplate

    # Opinionated / often wrong
    # - ireturn              # "return concrete types" - often incorrect for interfaces
    # - embeddedstructfieldcheck  # strict embedded field ordering - too pedantic

    # i18n / niche
    # - gosmopolitan         # i18n/l10n anti-patterns - very niche use case

    # Deprecated
    # - wsl                  # deprecated - using wsl_v5 instead

formatters:
  enable:
    - gofumpt
    - goimports
