# yaml-language-server: $schema=https://raw.githubusercontent.com/monkescience/yeet/main/yeet.schema.json

versioning: semver
branch: main
provider: auto

targets:
  vital:
    type: path
    path: .
    tag_prefix: v
